userName = input("What is you name? ")
favFood = input("what is your favorite food? " )
favMusic = input("What is your favorite artist? ")
userLocation = input("What is your address? ")
print()
print("Hi " + userName + ", here are your survey results.")
print("Favorite food: " + favFood)
print("Favorite artist: " + favMusic)
print("Address: " + userLocation)
print("You rock!!")